CREATE DATABASE salestime;
use salestime;
CREATE TABLE cliente
(
ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL, 
TEL VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
ENDERECO VARCHAR(30) NOT NULL,
PRIMARY KEY (ID_CLIENTE)
);